openapi: '3.0.3'
info:
  version: '1.0.0'
  title: Базовые модели для запросов
paths: { }

components:
  schemas:
    WorkerStatistics:
      description: Кол-во кадров с детекцией каждой эмоцции
      type: object
      properties:
        worker_id:
          type: integer
        timestammp:
          type: integer
        sex:
          type: boolean
        age_group:
          description: 0 - child; 1 - young; 2 - adults; 3 - old_man
          type: integer
        consultation_time:
          description: sec
          type: integer
        anger:
          type: integer
        fear:
          type: integer
        happy:
          type: integer
        neutral:
          type: integer
        sadness:
          type: integer
        surprized:
          type: integer