openapi: '3.0.3'
info:
  version: '1.0.0'
  title: Базовые модели для запросов
paths: { }

components:
  schemas:
    #messages
    GuiToServerRegular:
      description: Регулярное сообщение от гуи (нужно для сбора статистики как часто заказчик пользуется приложением)
      type: object
      properties:
        userName:
          type: string
    GuiToServerRequest:
      description: Запрос на получение информации о конкретных работниках
      type: object
      properties:
        workerIndiсes:
          type: array
          items:
            type: int
    ServerToGuiResponse:
      description: Запрос на получение информации о конкретном работнике
      type: object
      properties:
        workers:
          type: array
          items:
            $ref: "#/components/schemas/WorkerDiagnostic"
    WorkerDiagnostic:
      description: Процентное соотношение каждой эмоции
      type: object
      properties:
        workerId:
          type: int
        anger:
          type: int
        fear:
          type: int
        happy:
          type: int
        neutral:
          type: int
        sadness:
          type: int
        surprized:
          type: int


