version: "3"
services:
  rabbitmq:
    image: rabbitmq:latest
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=$RM_USER
      - RABBITMQ_DEFAULT_PASS=$RM_PASSWORD
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    networks:
      - rabbitmq_net

  db:
    container_name: db
    image: postgres:14.0-alpine
    hostname: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5434:5432"
    restart: always

  client:
    container_name: client
    build: client
    ports:
      - "80:80"


networks:
  rabbitmq_net:
    driver: bridge
